/**
 * Fund a participant wallet with tokens from each pod member's ERC-20 contract.
 *
 * Reads Alice/Bob/Carol's private keys from solutions/test-wallets.json
 * (generated by deploy-pod.ts) and transfers 100 tokens from each persona
 * to the recipient address provided as a CLI argument.
 *
 * Usage:
 *   npx tsx solutions/fund-wallet.ts 0xYourWalletAddress
 *
 * Prerequisites:
 *   - solutions/test-wallets.json exists (run deploy-pod.ts first)
 */

import { createWalletClient, createPublicClient, http, parseEther, formatEther } from "viem";
import { baseSepolia } from "viem/chains";
import { privateKeyToAccount } from "viem/accounts";
import { readFileSync } from "fs";
import { resolve } from "path";

type TestWallet = {
  owner: string;
  privateKey: `0x${string}`;
  address: string;
  tokenAddress: `0x${string}`;
  tokenSymbol: string;
  marketAddress: string;
  question: string;
};

const TRANSFER_AMOUNT = parseEther("100");

const erc20Abi = [
  {
    inputs: [{ name: "account", type: "address" }],
    name: "balanceOf",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "to", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    name: "transfer",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "symbol",
    outputs: [{ name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
] as const;

function loadEnvFile(filePath: string): Record<string, string> {
  const env: Record<string, string> = {};
  try {
    const content = readFileSync(filePath, "utf-8");
    for (const line of content.split("\n")) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const eqIndex = trimmed.indexOf("=");
      if (eqIndex === -1) continue;
      env[trimmed.slice(0, eqIndex).trim()] = trimmed.slice(eqIndex + 1).trim();
    }
  } catch {
    // intentional: missing .env.local is fine, we fall back to process.env
  }
  return env;
}

async function main() {
  const recipient = process.argv[2] as `0x${string}` | undefined;
  if (!recipient || !/^0x[0-9a-fA-F]{40}$/.test(recipient)) {
    console.error("Usage: npx tsx solutions/fund-wallet.ts <recipient-address>");
    console.error("  e.g. npx tsx solutions/fund-wallet.ts 0xAbC123...");
    process.exit(1);
  }

  const solutionsDir = resolve(import.meta.dirname ?? __dirname, ".");
  const walletsPath = resolve(solutionsDir, "test-wallets.json");

  let wallets: TestWallet[];
  try {
    wallets = JSON.parse(readFileSync(walletsPath, "utf-8"));
  } catch {
    console.error(`Error: ${walletsPath} not found. Run deploy-pod.ts first.`);
    process.exit(1);
  }

  const envFile = loadEnvFile(resolve(process.cwd(), ".env.local"));
  const rpcUrl = envFile.BASE_SEPOLIA_RPC || process.env.BASE_SEPOLIA_RPC || "https://sepolia.base.org";
  const publicClient = createPublicClient({ chain: baseSepolia, transport: http(rpcUrl) });

  console.log(`\nRecipient: ${recipient}`);
  console.log(`Amount:    ${formatEther(TRANSFER_AMOUNT)} tokens from each persona\n`);

  for (const wallet of wallets) {
    const account = privateKeyToAccount(wallet.privateKey);
    const walletClient = createWalletClient({ account, chain: baseSepolia, transport: http(rpcUrl) });

    const balance = await publicClient.readContract({
      address: wallet.tokenAddress,
      abi: erc20Abi,
      functionName: "balanceOf",
      args: [account.address],
    });

    console.log(`[${wallet.owner}] ${wallet.tokenSymbol} (${wallet.tokenAddress})`);
    console.log(`  ${wallet.owner}'s balance: ${formatEther(balance)}`);

    if (balance < TRANSFER_AMOUNT) {
      console.log(`  ⚠ Insufficient balance — skipping (need ${formatEther(TRANSFER_AMOUNT)}, have ${formatEther(balance)})\n`);
      continue;
    }

    const hash = await walletClient.writeContract({
      address: wallet.tokenAddress,
      abi: erc20Abi,
      functionName: "transfer",
      args: [recipient, TRANSFER_AMOUNT],
    });

    console.log(`  ✓ Tx sent: ${hash}`);

    const receipt = await publicClient.waitForTransactionReceipt({ hash });
    console.log(`  ✓ Confirmed in block ${receipt.blockNumber} (status: ${receipt.status})\n`);
  }

  console.log("Done!");
}

main().catch((err) => {
  console.error("Fatal error:", err.message ?? err);
  process.exit(1);
});
